# Generated by Django 2.2 on 2019-04-28 05:55

from django.db import migrations
from django.utils.text import slugify
import os
import json
from ..models import Product, Ingredient

JSON_PATH = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '..', '..', 'productos.json'))

INGREDIENTS_JSON_PATH = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '..', '..', 'ingredients.json'))


def populate_products(apps, schema_editor):
    fs = open(JSON_PATH, 'r')
    fs2 = open(INGREDIENTS_JSON_PATH, 'r')
    data = json.load(fs)
    ingredients_data = json.load(fs2)
    product_model = apps.get_model('bodega', 'Product')
    for product in data:
        product = product_model.objects.create(sku=int(product['sku']),
                                               name = product['nombre'],
                                               cost = int(product['costo']) if product['costo'] != "" else 0,
                                               price=int(product['precio']) if product['precio'] != "" else 0,
                                               duration=float(product['duracion(hrs)']),
                                               batch=int(product['lote produccion']),
                                               used_by=int(product["usado por"]),
                                               production_time=int(product['tiempo produccion(mins)']),
                                               productors=product["grupos productores"],
                                               p_type = product['produccion(tipo)'])
        product.save()
    
    for line in ingredients_data:
        product_instance = Product.objects.get(pk=int(line['sku_producto']))
        ingredient_instance = Product.objects.get(pk=int(line['sku_ingrediente']))
        new_ingredient = Ingredient.objects.create(sku_product=product_instance,
                                                   sku_ingredient=ingredient_instance,
                                                   production_batch=int(line['lote produccion']),
                                                   volume_in_store=int(float(line['bodega'])))
        new_ingredient.save()
                



class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_products),
    ]
