# Generated by Django 2.2 on 2019-04-28 05:55


from django.db import migrations
from django.utils.text import slugify
import os
import json

JSON_PATH = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '..', '..', 'productos.json'))


def populate_products(apps, schema_editor):
    fs = open(JSON_PATH, 'r')
    data = json.load(fs)
    product_model = apps.get_model('bodega', 'Product')
    for product in data:
        product = product_model.objects.create(sku=int(product['sku']),
                                               name=product['nombre'],
                                               description=product['descripcion'],
                                               slug=slugify(product['nombre']),
                                               price=int(
                                                   product['precio'][1:].replace(',', "")) if product['precio'] else None,
                                               duration=float(
                                                   product['duracion']),
                                               equivalence=float(
                                                   product['equivalencia']),
                                               unit=product['unidad'],
                                               batch=int(product['lote']),
                                               production_time=int(product['tiempo_esperado']))
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_products),
    ]
