# Generated by Django 2.2 on 2019-04-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_auto_20190428_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='group',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.CharField(default='processing', max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='vencimiento',
            field=models.DateField(null=True),
        ),
    ]
