# Generated by Django 2.2 on 2019-04-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_auto_20190429_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='vencimiento',
            new_name='deadline',
        ),
    ]
