# Generated by Django 2.2 on 2019-06-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_purchaseorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='finished',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sended',
            field=models.IntegerField(default=0),
        ),
    ]
