# Generated by Django 2.2 on 2019-04-29 22:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_auto_20190429_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='used_by',
            field=models.IntegerField(null=True),
        ),
    ]
