# Generated by Django 2.2 on 2019-04-30 05:15

from django.db import migrations

import os
import json


JSON_PATH = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '..', '..', 'productos.json'))


def populate_used_by(apps, schema_editor):
    fs = open(JSON_PATH, 'r')
    data = json.load(fs)
    product_model = apps.get_model('bodega', 'Product')
    for product in data:
        product = product_model.objects.filter(sku=int(product['sku'])).update(used_by=int(product['usado_por']))

class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_product_used_by'),
    ]

    operations = [
        migrations.RunPython(populate_used_by),
    ]
